name: PHPCS

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Install WordPress Coding Standards
        run: |
          composer global require wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer
      - name: Run PHPCS
        run: |
          ~/.composer/vendor/bin/phpcs -q --report=full


